### ISSUE TITLE
奇怪的人出现了！

### ISSUE THREAD

**Issue by j1g5awi** [maxesisn/nonedice#1]
您好，我也是个致力于在 nonebot 框架上复刻溯洄的 Dice！ 插件的人，这是我的项目仓库：[ NoDice ](https://github.com/thereisnodice/nodice)

我的项目的目标是松耦合（即可以完美迁移到其他未大幅改动的 nonebot 框架上），目前已经实现了复杂掷骰公式，人物生成以及最基本的牌堆，正准备通过链接 sqlite 数据库以实现群黑名单，人物卡等一系列需要数据库的功能。

同样的，我也打算在寒假开发 Dice! 插件的 nonebot2 版本，也许我们可以合作？

**Comment by maxesisn** [comment]
您好，目前该项目处于开发阶段，确实还有一些您提及的功能没有考虑到，因为我个人所在的跑团群并不太依赖骰娘的部分扩展功能，在没有硬需求的情况下，完美实现功能也就相对困难一些（主要是懒）。

我看了一下您的项目，和我目前的项目思路有共通之处，架构也比较相似，合作开发确实是可行的，因为我个人对Dice!插件全部功能的理解也较为有限，**如果您想要合作的话，拉我进组织就可以了。**

另外，如果迁移到nb2框架的话，与您完美迁移到其它nb1框架上的目标可能会有冲突需要解决，期望能在nodice项目内进一步看到您的迁移规划。
